-- Urbino phase 02 baseline. Application IDs are generated by the application.
CREATE TABLE tenants (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
    status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    policy_version BIGINT NOT NULL CHECK (policy_version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, currency)
);

CREATE TABLE projects (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
    status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT projects_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE users (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    display_name TEXT NOT NULL CHECK (length(display_name) BETWEEN 1 AND 200),
    status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT users_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE price_versions (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    effective_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'retired')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, id, currency),
    CONSTRAINT price_versions_tenant_currency_fk FOREIGN KEY (tenant_id, currency) REFERENCES tenants(id, currency)
);

CREATE TABLE price_items (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    price_version_id UUID NOT NULL,
    model TEXT NOT NULL CHECK (length(model) BETWEEN 1 AND 200),
    tier TEXT NOT NULL CHECK (length(tier) BETWEEN 1 AND 80),
    dimension TEXT NOT NULL CHECK (dimension IN ('input', 'input_cached', 'output', 'reasoning', 'cache_read', 'cache_write')),
    unit_price NUMERIC(30, 12) NOT NULL CHECK (unit_price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT price_items_version_fk FOREIGN KEY (tenant_id, price_version_id) REFERENCES price_versions(tenant_id, id),
    CONSTRAINT price_items_unique_dimension UNIQUE (tenant_id, price_version_id, model, tier, dimension)
);

CREATE TABLE requests (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    project_id UUID NOT NULL,
    user_id UUID,
    idempotency_digest BYTEA,
    body_digest BYTEA NOT NULL,
    model TEXT NOT NULL CHECK (length(model) BETWEEN 1 AND 200),
    protocol TEXT NOT NULL CHECK (length(protocol) BETWEEN 1 AND 40),
    status TEXT NOT NULL,
    dispatch_status TEXT NOT NULL,
    usage_status TEXT NOT NULL,
    price_version_id UUID,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT requests_project_fk FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id),
    CONSTRAINT requests_user_fk FOREIGN KEY (tenant_id, user_id) REFERENCES users(tenant_id, id),
    CONSTRAINT requests_price_version_fk FOREIGN KEY (tenant_id, price_version_id) REFERENCES price_versions(tenant_id, id),
    CONSTRAINT requests_finished_after_start CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT requests_idempotency_unique UNIQUE (tenant_id, idempotency_digest)
);

CREATE TABLE request_attempts (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    request_id UUID NOT NULL,
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    account_id UUID,
    credential_version BIGINT NOT NULL CHECK (credential_version > 0),
    egress_version BIGINT NOT NULL CHECK (egress_version > 0),
    upstream_request_id TEXT,
    dispatch_phase TEXT NOT NULL,
    result_class TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT attempts_request_fk FOREIGN KEY (tenant_id, request_id) REFERENCES requests(tenant_id, id),
    CONSTRAINT attempts_business_key_unique UNIQUE (tenant_id, request_id, attempt_no)
);

CREATE TABLE billing_accounts (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    posted_balance_micros BIGINT NOT NULL,
    held_micros BIGINT NOT NULL CHECK (held_micros >= 0),
    version BIGINT NOT NULL CHECK (version > 0),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT billing_accounts_tenant_currency_fk FOREIGN KEY (tenant_id, currency) REFERENCES tenants(id, currency),
    CONSTRAINT billing_accounts_nonnegative_available CHECK (posted_balance_micros >= held_micros)
);

CREATE TABLE settlements (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    request_id UUID NOT NULL,
    business_key TEXT NOT NULL CHECK (length(business_key) BETWEEN 1 AND 200),
    price_version_id UUID NOT NULL,
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    price_snapshot JSONB NOT NULL CHECK (jsonb_typeof(price_snapshot) = 'object'),
    amount_micros BIGINT NOT NULL CHECK (amount_micros >= 0),
    status TEXT NOT NULL CHECK (status IN ('pending', 'posted', 'pending_reconciliation', 'voided')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT settlements_request_fk FOREIGN KEY (tenant_id, request_id) REFERENCES requests(tenant_id, id),
    CONSTRAINT settlements_price_fk FOREIGN KEY (tenant_id, price_version_id, currency) REFERENCES price_versions(tenant_id, id, currency),
    CONSTRAINT settlements_business_key_unique UNIQUE (tenant_id, business_key),
    CONSTRAINT settlements_request_unique UNIQUE (tenant_id, request_id)
);

CREATE TABLE journal_transactions (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    business_key TEXT NOT NULL CHECK (length(business_key) BETWEEN 1 AND 200),
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, id, currency),
    CONSTRAINT journal_business_key_unique UNIQUE (tenant_id, business_key),
    CONSTRAINT journal_tenant_currency_fk FOREIGN KEY (tenant_id, currency) REFERENCES tenants(id, currency)
);

CREATE TABLE journal_entries (
    tenant_id UUID NOT NULL,
    id UUID NOT NULL,
    transaction_id UUID NOT NULL,
    currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    account_ref TEXT NOT NULL CHECK (length(account_ref) BETWEEN 1 AND 200),
    amount_micros BIGINT NOT NULL CHECK (amount_micros <> 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    CONSTRAINT journal_entries_transaction_fk FOREIGN KEY (tenant_id, transaction_id, currency) REFERENCES journal_transactions(tenant_id, id, currency)
);

CREATE OR REPLACE FUNCTION urbino_reject_immutable_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'immutable ledger row';
END;
$$;

CREATE OR REPLACE FUNCTION urbino_validate_published_price() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    version_status TEXT;
    version_tenant UUID;
    version_id UUID;
BEGIN
    version_tenant := NEW.tenant_id;
    IF TG_TABLE_NAME = 'price_items' THEN
        version_id := NEW.price_version_id;
        SELECT status INTO version_status FROM price_versions WHERE tenant_id = version_tenant AND id = version_id;
    ELSE
        version_id := NEW.id;
        version_status := NEW.status;
    END IF;
    IF version_status = 'published' AND NOT EXISTS (
        SELECT 1 FROM price_items
        WHERE tenant_id = version_tenant AND price_version_id = version_id
    ) THEN
        RAISE EXCEPTION 'published price version requires at least one price item';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION urbino_validate_journal_balance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    entry_count BIGINT;
    entry_total BIGINT;
    transaction_tenant UUID;
    target_transaction_id UUID;
BEGIN
    transaction_tenant := NEW.tenant_id;
    IF TG_TABLE_NAME = 'journal_entries' THEN
        target_transaction_id := NEW.transaction_id;
    ELSE
        target_transaction_id := NEW.id;
    END IF;
    SELECT count(*), COALESCE(sum(je.amount_micros), 0)
      INTO entry_count, entry_total
      FROM journal_entries AS je
     WHERE je.tenant_id = transaction_tenant AND je.transaction_id = target_transaction_id;
    IF entry_count < 2 OR entry_total <> 0 THEN
        RAISE EXCEPTION 'journal transaction must have at least two balanced entries';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION urbino_reject_published_price_item_change() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    old_status TEXT;
    new_status TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT status INTO new_status FROM price_versions WHERE tenant_id = NEW.tenant_id AND id = NEW.price_version_id;
        IF new_status = 'published' THEN
            RAISE EXCEPTION 'published price items are immutable';
        END IF;
        RETURN NEW;
    END IF;
    SELECT status INTO old_status FROM price_versions WHERE tenant_id = OLD.tenant_id AND id = OLD.price_version_id;
    IF old_status = 'published' THEN
        RAISE EXCEPTION 'published price items are immutable';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        SELECT status INTO new_status FROM price_versions WHERE tenant_id = NEW.tenant_id AND id = NEW.price_version_id;
        IF new_status = 'published' THEN
            RAISE EXCEPTION 'published price items are immutable';
        END IF;
        RETURN NEW;
    END IF;
    RETURN OLD;
END;
$$;

CREATE TRIGGER price_items_published_immutable BEFORE INSERT OR UPDATE OR DELETE ON price_items
FOR EACH ROW EXECUTE FUNCTION urbino_reject_published_price_item_change();

CREATE TRIGGER journal_transactions_immutable BEFORE UPDATE OR DELETE ON journal_transactions
FOR EACH ROW EXECUTE FUNCTION urbino_reject_immutable_change();

CREATE TRIGGER journal_entries_immutable BEFORE UPDATE OR DELETE ON journal_entries
FOR EACH ROW EXECUTE FUNCTION urbino_reject_immutable_change();

CREATE TRIGGER price_versions_immutable AFTER UPDATE OR DELETE ON price_versions
FOR EACH ROW WHEN (OLD.status = 'published') EXECUTE FUNCTION urbino_reject_immutable_change();

CREATE CONSTRAINT TRIGGER price_versions_require_items
AFTER INSERT OR UPDATE OF status ON price_versions
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION urbino_validate_published_price();

CREATE CONSTRAINT TRIGGER price_items_require_published_version_items
AFTER INSERT ON price_items
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION urbino_validate_published_price();

CREATE CONSTRAINT TRIGGER journal_transactions_must_balance
AFTER INSERT ON journal_transactions
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION urbino_validate_journal_balance();

CREATE CONSTRAINT TRIGGER journal_entries_must_balance
AFTER INSERT ON journal_entries
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION urbino_validate_journal_balance();

CREATE INDEX requests_scope_created_idx ON requests (tenant_id, project_id, created_at DESC);
CREATE INDEX price_versions_lookup_idx ON price_versions (tenant_id, status, effective_at DESC);
CREATE INDEX price_items_version_idx ON price_items (tenant_id, price_version_id);
CREATE INDEX settlements_request_idx ON settlements (tenant_id, request_id);
CREATE INDEX journal_entries_transaction_idx ON journal_entries (tenant_id, transaction_id);
