-- +goose Up
CREATE SCHEMA IF NOT EXISTS urbino;
CREATE TABLE IF NOT EXISTS urbino.schema_version (singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton), version bigint NOT NULL CHECK (version > 0));
INSERT INTO urbino.schema_version(singleton, version) VALUES (true, 1) ON CONFLICT (singleton) DO UPDATE SET version = EXCLUDED.version;
CREATE TABLE IF NOT EXISTS urbino.tenants (id uuid PRIMARY KEY, name text NOT NULL, status text NOT NULL, currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'), policy_version text NOT NULL, UNIQUE (id, id));
CREATE TABLE IF NOT EXISTS urbino.users (tenant_id uuid NOT NULL, id uuid NOT NULL, display_name text NOT NULL, status text NOT NULL, PRIMARY KEY (tenant_id,id), FOREIGN KEY (tenant_id) REFERENCES urbino.tenants(id));
CREATE TABLE IF NOT EXISTS urbino.projects (tenant_id uuid NOT NULL, id uuid NOT NULL, name text NOT NULL, status text NOT NULL, PRIMARY KEY (tenant_id,id), FOREIGN KEY (tenant_id) REFERENCES urbino.tenants(id));
CREATE TABLE IF NOT EXISTS urbino.project_members (tenant_id uuid NOT NULL, project_id uuid NOT NULL, user_id uuid NOT NULL, role text NOT NULL, PRIMARY KEY (tenant_id,project_id,user_id), FOREIGN KEY (tenant_id,project_id) REFERENCES urbino.projects(tenant_id,id), FOREIGN KEY (tenant_id,user_id) REFERENCES urbino.users(tenant_id,id));
CREATE TABLE IF NOT EXISTS urbino.api_keys (tenant_id uuid NOT NULL, project_id uuid NOT NULL, user_id uuid NOT NULL, public_id text PRIMARY KEY, secret_digest bytea NOT NULL, digest_key_id text NOT NULL, scopes text[] NOT NULL, model_policy_id text, status text NOT NULL, expires_at timestamptz, revoked_at timestamptz, auth_version bigint NOT NULL DEFAULT 1, FOREIGN KEY (tenant_id,project_id) REFERENCES urbino.projects(tenant_id,id), FOREIGN KEY (tenant_id,user_id) REFERENCES urbino.users(tenant_id,id));
CREATE TABLE IF NOT EXISTS urbino.price_versions (id uuid PRIMARY KEY, version bigint NOT NULL UNIQUE, currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'), effective_at timestamptz NOT NULL, published_at timestamptz NOT NULL, immutable boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS urbino.price_items (price_version_id uuid NOT NULL REFERENCES urbino.price_versions(id), model text NOT NULL, tier text NOT NULL, dimension text NOT NULL, unit_price numeric(30,12) NOT NULL CHECK (unit_price >= 0), PRIMARY KEY (price_version_id,model,tier,dimension));
CREATE TABLE IF NOT EXISTS urbino.requests (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, project_id uuid NOT NULL, user_id uuid, key_public_id text, request_id text NOT NULL, idempotency_digest bytea, body_digest bytea NOT NULL, model text NOT NULL, protocol text NOT NULL, status text NOT NULL, dispatch_status text NOT NULL, usage_status text NOT NULL, started_at timestamptz NOT NULL, finished_at timestamptz, config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (tenant_id,id), UNIQUE (tenant_id,request_id), UNIQUE (tenant_id,idempotency_digest), FOREIGN KEY (tenant_id,project_id) REFERENCES urbino.projects(tenant_id,id), FOREIGN KEY (tenant_id,user_id) REFERENCES urbino.users(tenant_id,id));
CREATE TABLE IF NOT EXISTS urbino.request_attempts (request_id uuid NOT NULL REFERENCES urbino.requests(id), attempt_no integer NOT NULL CHECK (attempt_no > 0), id uuid PRIMARY KEY, tenant_id uuid NOT NULL, account_id uuid, credential_version bigint, egress_version text, upstream_request_id text, dispatch_phase text NOT NULL, result_class text NOT NULL, status text NOT NULL, UNIQUE (request_id,attempt_no), UNIQUE (request_id,id), FOREIGN KEY (tenant_id,request_id) REFERENCES urbino.requests(tenant_id,id));
CREATE TABLE IF NOT EXISTS urbino.usage_events (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, request_id uuid NOT NULL, attempt_id uuid NOT NULL, source text NOT NULL, event_key text NOT NULL, completeness text NOT NULL, input_total bigint, input_uncached bigint, cache_read bigint, cache_write bigint, output_total bigint, reasoning bigint, is_estimate boolean NOT NULL DEFAULT false, provider_version text, UNIQUE (attempt_id,event_key), FOREIGN KEY (tenant_id,request_id) REFERENCES urbino.requests(tenant_id,id), FOREIGN KEY (request_id,attempt_id) REFERENCES urbino.request_attempts(request_id,id));
CREATE TABLE IF NOT EXISTS urbino.billing_accounts (tenant_id uuid NOT NULL, id uuid NOT NULL, currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'), posted_balance_micros bigint NOT NULL DEFAULT 0 CHECK (posted_balance_micros >= 0), held_micros bigint NOT NULL DEFAULT 0 CHECK (held_micros >= 0), version bigint NOT NULL DEFAULT 1, PRIMARY KEY (tenant_id,id), UNIQUE (tenant_id));
CREATE TABLE IF NOT EXISTS urbino.balance_holds (tenant_id uuid NOT NULL, request_id uuid PRIMARY KEY REFERENCES urbino.requests(id), account_id uuid NOT NULL, amount_micros bigint NOT NULL CHECK (amount_micros >= 0), state text NOT NULL, created_at timestamptz NOT NULL, deadline timestamptz NOT NULL, FOREIGN KEY (tenant_id,account_id) REFERENCES urbino.billing_accounts(tenant_id,id), FOREIGN KEY (tenant_id,request_id) REFERENCES urbino.requests(tenant_id,id));
CREATE TABLE IF NOT EXISTS urbino.journal_transactions (id uuid PRIMARY KEY, business_key text NOT NULL UNIQUE, currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'), created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS urbino.journal_entries (id uuid PRIMARY KEY, transaction_id uuid NOT NULL REFERENCES urbino.journal_transactions(id), account_ref text NOT NULL, amount_micros bigint NOT NULL, currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'));
CREATE TABLE IF NOT EXISTS urbino.settlements (tenant_id uuid NOT NULL, request_id uuid PRIMARY KEY REFERENCES urbino.requests(id), price_snapshot jsonb NOT NULL, usage_event_id uuid, amount_micros bigint NOT NULL CHECK (amount_micros >= 0), status text NOT NULL, created_at timestamptz NOT NULL, FOREIGN KEY (tenant_id,request_id) REFERENCES urbino.requests(tenant_id,id));
CREATE OR REPLACE FUNCTION urbino.reject_journal_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'journal rows are immutable'; END; $$;
DROP TRIGGER IF EXISTS journal_transactions_immutable ON urbino.journal_transactions;
CREATE TRIGGER journal_transactions_immutable BEFORE UPDATE OR DELETE ON urbino.journal_transactions FOR EACH ROW EXECUTE FUNCTION urbino.reject_journal_mutation();
DROP TRIGGER IF EXISTS journal_entries_immutable ON urbino.journal_entries;
CREATE TRIGGER journal_entries_immutable BEFORE UPDATE OR DELETE ON urbino.journal_entries FOR EACH ROW EXECUTE FUNCTION urbino.reject_journal_mutation();
CREATE OR REPLACE FUNCTION urbino.check_journal_balance() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE total bigint; BEGIN SELECT COALESCE(SUM(amount_micros),0) INTO total FROM urbino.journal_entries WHERE transaction_id=NEW.transaction_id; IF total <> 0 THEN RAISE EXCEPTION 'journal transaction is not balanced'; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS journal_entries_balance ON urbino.journal_entries;
CREATE CONSTRAINT TRIGGER journal_entries_balance AFTER INSERT OR UPDATE ON urbino.journal_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION urbino.check_journal_balance();
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'urbino_runtime') THEN GRANT USAGE ON SCHEMA urbino TO urbino_runtime; GRANT SELECT ON ALL TABLES IN SCHEMA urbino TO urbino_runtime; GRANT INSERT ON urbino.requests,urbino.request_attempts,urbino.usage_events TO urbino_runtime; END IF; END $$;
-- +goose Down
-- Intentionally unsupported: use an application-first compatible rollback.
