// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditEventResult.
const (
	Failed   AuditEventResult = "failed"
	Rejected AuditEventResult = "rejected"
	Success  AuditEventResult = "success"
)

// Valid indicates whether the value is a known member of the AuditEventResult enum.
func (e AuditEventResult) Valid() bool {
	switch e {
	case Failed:
		return true
	case Rejected:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityDescriptorStatus.
const (
	CapabilityDescriptorStatusDisabled              CapabilityDescriptorStatus = "disabled"
	CapabilityDescriptorStatusEnabled               CapabilityDescriptorStatus = "enabled"
	CapabilityDescriptorStatusRequiresAuthorization CapabilityDescriptorStatus = "requires_authorization"
	CapabilityDescriptorStatusUnsupported           CapabilityDescriptorStatus = "unsupported"
)

// Valid indicates whether the value is a known member of the CapabilityDescriptorStatus enum.
func (e CapabilityDescriptorStatus) Valid() bool {
	switch e {
	case CapabilityDescriptorStatusDisabled:
		return true
	case CapabilityDescriptorStatusEnabled:
		return true
	case CapabilityDescriptorStatusRequiresAuthorization:
		return true
	case CapabilityDescriptorStatusUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeBillingUnavailable       ErrorCode = "billing_unavailable"
	ErrorCodeCredentialRequiresReauth ErrorCode = "credential_requires_reauth"
	ErrorCodeInvalidRequest           ErrorCode = "invalid_request"
	ErrorCodePermissionDenied         ErrorCode = "permission_denied"
	ErrorCodeQuotaExceeded            ErrorCode = "quota_exceeded"
	ErrorCodeResourceNotFound         ErrorCode = "resource_not_found"
	ErrorCodeUnauthorized             ErrorCode = "unauthorized"
	ErrorCodeUnsupportedCapability    ErrorCode = "unsupported_capability"
	ErrorCodeUpstreamResultUnknown    ErrorCode = "upstream_result_unknown"
	ErrorCodeUpstreamUnavailable      ErrorCode = "upstream_unavailable"
	ErrorCodeVersionConflict          ErrorCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeBillingUnavailable:
		return true
	case ErrorCodeCredentialRequiresReauth:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodeQuotaExceeded:
		return true
	case ErrorCodeResourceNotFound:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupportedCapability:
		return true
	case ErrorCodeUpstreamResultUnknown:
		return true
	case ErrorCodeUpstreamUnavailable:
		return true
	case ErrorCodeVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for ModelDescriptorProtocol.
const (
	AnthropicMessages     ModelDescriptorProtocol = "anthropic_messages"
	GeminiGenerateContent ModelDescriptorProtocol = "gemini_generate_content"
	OpenaiChat            ModelDescriptorProtocol = "openai_chat"
	OpenaiEmbeddings      ModelDescriptorProtocol = "openai_embeddings"
	OpenaiResponses       ModelDescriptorProtocol = "openai_responses"
)

// Valid indicates whether the value is a known member of the ModelDescriptorProtocol enum.
func (e ModelDescriptorProtocol) Valid() bool {
	switch e {
	case AnthropicMessages:
		return true
	case GeminiGenerateContent:
		return true
	case OpenaiChat:
		return true
	case OpenaiEmbeddings:
		return true
	case OpenaiResponses:
		return true
	default:
		return false
	}
}

// Defines values for TenantStatus.
const (
	TenantStatusActive   TenantStatus = "active"
	TenantStatusArchived TenantStatus = "archived"
	TenantStatusDisabled TenantStatus = "disabled"
)

// Valid indicates whether the value is a known member of the TenantStatus enum.
func (e TenantStatus) Valid() bool {
	switch e {
	case TenantStatusActive:
		return true
	case TenantStatusArchived:
		return true
	case TenantStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTenantRequestStatus.
const (
	UpdateTenantRequestStatusActive   UpdateTenantRequestStatus = "active"
	UpdateTenantRequestStatusArchived UpdateTenantRequestStatus = "archived"
	UpdateTenantRequestStatusDisabled UpdateTenantRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateTenantRequestStatus enum.
func (e UpdateTenantRequestStatus) Valid() bool {
	switch e {
	case UpdateTenantRequestStatusActive:
		return true
	case UpdateTenantRequestStatusArchived:
		return true
	case UpdateTenantRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string             `json:"action"`
	Id         openapi_types.UUID `json:"id"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	OccurredAt time.Time          `json:"occurred_at"`
	Result     AuditEventResult   `json:"result"`
	Target     string             `json:"target"`
}

// AuditEventResult defines model for AuditEvent.Result.
type AuditEventResult string

// CapabilityDescriptor defines model for CapabilityDescriptor.
type CapabilityDescriptor struct {
	Name      string                     `json:"name"`
	Protocols []string                   `json:"protocols"`
	Status    CapabilityDescriptorStatus `json:"status"`
	Version   string                     `json:"version"`
}

// CapabilityDescriptorStatus defines model for CapabilityDescriptor.Status.
type CapabilityDescriptorStatus string

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	Currency string `json:"currency"`
	Name     string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code      ErrorCode          `json:"code"`
	Details   *map[string]string `json:"details,omitempty"`
	Message   string             `json:"message"`
	RequestId openapi_types.UUID `json:"request_id"`
	Retryable bool               `json:"retryable"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// ModelDescriptor defines model for ModelDescriptor.
type ModelDescriptor struct {
	Capabilities []string                `json:"capabilities"`
	Enabled      bool                    `json:"enabled"`
	Protocol     ModelDescriptorProtocol `json:"protocol"`
	PublicName   string                  `json:"public_name"`
}

// ModelDescriptorProtocol defines model for ModelDescriptor.Protocol.
type ModelDescriptorProtocol string

// Tenant defines model for Tenant.
type Tenant struct {
	Currency      string             `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	PolicyVersion int64              `json:"policy_version"`
	Status        TenantStatus       `json:"status"`
	Version       int64              `json:"version"`
}

// TenantStatus defines model for Tenant.Status.
type TenantStatus string

// UpdateTenantRequest defines model for UpdateTenantRequest.
type UpdateTenantRequest struct {
	Name   *string                    `json:"name,omitempty"`
	Status *UpdateTenantRequestStatus `json:"status,omitempty"`
}

// UpdateTenantRequestStatus defines model for UpdateTenantRequest.Status.
type UpdateTenantRequestStatus string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// TenantID defines model for TenantID.
type TenantID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = Error

// TenantList defines model for TenantList.
type TenantList struct {
	Items      []Tenant `json:"items"`
	NextCursor *string  `json:"next_cursor,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Limit  *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	From   *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To     *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// ListTenantsParams defines parameters for ListTenants.
type ListTenantsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateTenantParams defines parameters for UpdateTenant.
type UpdateTenantParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = UpdateTenantRequest
