// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CapabilityDescriptorName.
const (
	AdminApi        CapabilityDescriptorName = "admin_api"
	ChatCompletions CapabilityDescriptorName = "chat_completions"
	Embeddings      CapabilityDescriptorName = "embeddings"
	Responses       CapabilityDescriptorName = "responses"
)

// Valid indicates whether the value is a known member of the CapabilityDescriptorName enum.
func (e CapabilityDescriptorName) Valid() bool {
	switch e {
	case AdminApi:
		return true
	case ChatCompletions:
		return true
	case Embeddings:
		return true
	case Responses:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityDescriptorScopes.
const (
	ModelsRead   CapabilityDescriptorScopes = "models:read"
	TenantsRead  CapabilityDescriptorScopes = "tenants:read"
	TenantsWrite CapabilityDescriptorScopes = "tenants:write"
	UsageRead    CapabilityDescriptorScopes = "usage:read"
)

// Valid indicates whether the value is a known member of the CapabilityDescriptorScopes enum.
func (e CapabilityDescriptorScopes) Valid() bool {
	switch e {
	case ModelsRead:
		return true
	case TenantsRead:
		return true
	case TenantsWrite:
		return true
	case UsageRead:
		return true
	default:
		return false
	}
}

// Defines values for CreateTenantRequestCurrency.
const (
	CreateTenantRequestCurrencyCNY CreateTenantRequestCurrency = "CNY"
	CreateTenantRequestCurrencyEUR CreateTenantRequestCurrency = "EUR"
	CreateTenantRequestCurrencyGBP CreateTenantRequestCurrency = "GBP"
	CreateTenantRequestCurrencyJPY CreateTenantRequestCurrency = "JPY"
	CreateTenantRequestCurrencyUSD CreateTenantRequestCurrency = "USD"
)

// Valid indicates whether the value is a known member of the CreateTenantRequestCurrency enum.
func (e CreateTenantRequestCurrency) Valid() bool {
	switch e {
	case CreateTenantRequestCurrencyCNY:
		return true
	case CreateTenantRequestCurrencyEUR:
		return true
	case CreateTenantRequestCurrencyGBP:
		return true
	case CreateTenantRequestCurrencyJPY:
		return true
	case CreateTenantRequestCurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeBadRequest            ErrorCode = "bad_request"
	ErrorCodePermissionDenied      ErrorCode = "permission_denied"
	ErrorCodeResourceNotFound      ErrorCode = "resource_not_found"
	ErrorCodeUnauthorized          ErrorCode = "unauthorized"
	ErrorCodeUnknown               ErrorCode = "unknown"
	ErrorCodeUnsupportedCapability ErrorCode = "unsupported_capability"
	ErrorCodeVersionConflict       ErrorCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeBadRequest:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodeResourceNotFound:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnknown:
		return true
	case ErrorCodeUnsupportedCapability:
		return true
	case ErrorCodeVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for TenantCurrency.
const (
	TenantCurrencyCNY TenantCurrency = "CNY"
	TenantCurrencyEUR TenantCurrency = "EUR"
	TenantCurrencyGBP TenantCurrency = "GBP"
	TenantCurrencyJPY TenantCurrency = "JPY"
	TenantCurrencyUSD TenantCurrency = "USD"
)

// Valid indicates whether the value is a known member of the TenantCurrency enum.
func (e TenantCurrency) Valid() bool {
	switch e {
	case TenantCurrencyCNY:
		return true
	case TenantCurrencyEUR:
		return true
	case TenantCurrencyGBP:
		return true
	case TenantCurrencyJPY:
		return true
	case TenantCurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for TenantStatus.
const (
	TenantStatusActive   TenantStatus = "active"
	TenantStatusDisabled TenantStatus = "disabled"
)

// Valid indicates whether the value is a known member of the TenantStatus enum.
func (e TenantStatus) Valid() bool {
	switch e {
	case TenantStatusActive:
		return true
	case TenantStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTenantRequestStatus.
const (
	UpdateTenantRequestStatusActive   UpdateTenantRequestStatus = "active"
	UpdateTenantRequestStatusDisabled UpdateTenantRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateTenantRequestStatus enum.
func (e UpdateTenantRequestStatus) Valid() bool {
	switch e {
	case UpdateTenantRequestStatusActive:
		return true
	case UpdateTenantRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// CapabilityDescriptor defines model for CapabilityDescriptor.
type CapabilityDescriptor struct {
	Enabled bool                         `json:"enabled"`
	Name    CapabilityDescriptorName     `json:"name"`
	Scopes  []CapabilityDescriptorScopes `json:"scopes"`
	Version string                       `json:"version"`
}

// CapabilityDescriptorName defines model for CapabilityDescriptor.Name.
type CapabilityDescriptorName string

// CapabilityDescriptorScopes defines model for CapabilityDescriptor.Scopes.
type CapabilityDescriptorScopes string

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	Currency CreateTenantRequestCurrency `json:"currency"`
	Name     string                      `json:"name"`
}

// CreateTenantRequestCurrency defines model for CreateTenantRequest.Currency.
type CreateTenantRequestCurrency string

// Error defines model for Error.
type Error struct {
	Code      ErrorCode          `json:"code"`
	Details   map[string]string  `json:"details"`
	Message   string             `json:"message"`
	RequestId openapi_types.UUID `json:"request_id"`
	Retryable bool               `json:"retryable"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Tenant defines model for Tenant.
type Tenant struct {
	Currency TenantCurrency     `json:"currency"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Status   TenantStatus       `json:"status"`
	Version  int64              `json:"version"`
}

// TenantCurrency defines model for Tenant.Currency.
type TenantCurrency string

// TenantStatus defines model for Tenant.Status.
type TenantStatus string

// TenantPage defines model for TenantPage.
type TenantPage struct {
	Items      []Tenant `json:"items"`
	NextCursor *string  `json:"next_cursor"`
}

// UpdateTenantRequest defines model for UpdateTenantRequest.
type UpdateTenantRequest struct {
	Name   *string                    `json:"name,omitempty"`
	Status *UpdateTenantRequestStatus `json:"status,omitempty"`
}

// UpdateTenantRequestStatus defines model for UpdateTenantRequest.Status.
type UpdateTenantRequestStatus string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int32

// TenantId defines model for TenantId.
type TenantId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unsupported defines model for Unsupported.
type Unsupported = Error

// ListTenantsParams defines parameters for ListTenants.
type ListTenantsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateTenantParams defines parameters for CreateTenant.
type CreateTenantParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateTenantParams defines parameters for UpdateTenant.
type UpdateTenantParams struct {
	IfMatch        IfMatch        `json:"If-Match"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = UpdateTenantRequest
